# Generated by Django 5.1.4 on 2025-01-03 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("in_progress", "В работе"),
                            ("in_delivery", "В доставке"),
                            ("completed", "Выполнен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="new",
                        max_length=15,
                    ),
                ),
                ("address", models.TextField()),
                ("delivery_date", models.DateField()),
                (
                    "delivery_time_interval",
                    models.CharField(
                        choices=[
                            ("09:00 - 11:00", "09:00 - 11:00"),
                            ("11:00 - 13:00", "11:00 - 13:00"),
                            ("13:00 - 15:00", "13:00 - 15:00"),
                            ("15:00 - 17:00", "15:00 - 17:00"),
                            ("17:00 - 19:00", "17:00 - 19:00"),
                            ("19:00 - 21:00", "19:00 - 21:00"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer_comment", models.CharField(blank=True, max_length=250)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "flower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="goods.flower"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="flowers",
            field=models.ManyToManyField(through="orders.OrderItem", to="goods.flower"),
        ),
    ]
