# Generated by Django 5.1.4 on 2025-01-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("orders_count", models.PositiveIntegerField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("orders_list_new", models.TextField(default="")),
                ("orders_list_in_progress", models.TextField(default="")),
                ("orders_list_in_delivery", models.TextField(default="")),
                ("orders_list_completed", models.TextField(default="")),
                ("orders_list_cancelled", models.TextField(default="")),
            ],
        ),
    ]
